module com.unifysweproject.hotelsupplymanagement {
    requires javafx.controls;
    requires javafx.fxml;

    requires org.slf4j;
    requires com.dlsc.formsfx;
    requires org.kordamp.ikonli.javafx;
    requires org.xerial.sqlitejdbc;

    exports com.unifisweproject.hotelsupplymanagement.company;
    opens com.unifisweproject.hotelsupplymanagement.company to javafx.fxml;
    exports com.unifisweproject.hotelsupplymanagement.contact;
    opens com.unifisweproject.hotelsupplymanagement.contact to javafx.fxml;
    opens com.unifisweproject.hotelsupplymanagement.supply to javafx.fxml;
    exports com.unifisweproject.hotelsupplymanagement.login;
    opens com.unifisweproject.hotelsupplymanagement.login to javafx.fxml;
    exports com.unifisweproject.hotelsupplymanagement.main;
    opens com.unifisweproject.hotelsupplymanagement.main to javafx.fxml;
    exports com.unifisweproject.hotelsupplymanagement.itemsInOrderAndSupply;
    opens com.unifisweproject.hotelsupplymanagement.itemsInOrderAndSupply to javafx.fxml;
    exports com.unifisweproject.hotelsupplymanagement.model;
    opens com.unifisweproject.hotelsupplymanagement.model to javafx.fxml;
    exports com.unifisweproject.hotelsupplymanagement.view;
    opens com.unifisweproject.hotelsupplymanagement.view to javafx.fxml;
    exports com.unifisweproject.hotelsupplymanagement.controller;
    opens com.unifisweproject.hotelsupplymanagement.controller to javafx.fxml;
    exports com.unifisweproject.hotelsupplymanagement.model.customer;
    opens com.unifisweproject.hotelsupplymanagement.model.customer to javafx.fxml;
    exports com.unifisweproject.hotelsupplymanagement.model.order;
    opens com.unifisweproject.hotelsupplymanagement.model.order to javafx.fxml;
    exports com.unifisweproject.hotelsupplymanagement.model.supply;
    opens com.unifisweproject.hotelsupplymanagement.model.supply to javafx.fxml;
    exports com.unifisweproject.hotelsupplymanagement.model.supplier;
    opens com.unifisweproject.hotelsupplymanagement.model.supplier to javafx.fxml;
    exports com.unifisweproject.hotelsupplymanagement.model.item;
    opens com.unifisweproject.hotelsupplymanagement.model.item to javafx.fxml;
    exports com.unifisweproject.hotelsupplymanagement.window.customer;
    opens com.unifisweproject.hotelsupplymanagement.window.customer to javafx.fxml;
    exports com.unifisweproject.hotelsupplymanagement.window.item;
    opens com.unifisweproject.hotelsupplymanagement.window.item to javafx.fxml;
    exports com.unifisweproject.hotelsupplymanagement.window.order;
    opens com.unifisweproject.hotelsupplymanagement.window.order to javafx.fxml;
    exports com.unifisweproject.hotelsupplymanagement.window.supplier;
    opens com.unifisweproject.hotelsupplymanagement.window.supplier to javafx.fxml;
    exports com.unifisweproject.hotelsupplymanagement.window.supply;
    opens com.unifisweproject.hotelsupplymanagement.window.supply to javafx.fxml;
    exports com.unifisweproject.hotelsupplymanagement.view.customer;
    opens com.unifisweproject.hotelsupplymanagement.view.customer to javafx.fxml;
    exports com.unifisweproject.hotelsupplymanagement.view.item;
    opens com.unifisweproject.hotelsupplymanagement.view.item to javafx.fxml;
    exports com.unifisweproject.hotelsupplymanagement.view.order;
    opens com.unifisweproject.hotelsupplymanagement.view.order to javafx.fxml;
    exports com.unifisweproject.hotelsupplymanagement.view.supplier;
    opens com.unifisweproject.hotelsupplymanagement.view.supplier to javafx.fxml;
    exports com.unifisweproject.hotelsupplymanagement.view.supply;
    opens com.unifisweproject.hotelsupplymanagement.view.supply to javafx.fxml;
    exports com.unifisweproject.hotelsupplymanagement.controller.customer;
    opens com.unifisweproject.hotelsupplymanagement.controller.customer to javafx.fxml;
    exports com.unifisweproject.hotelsupplymanagement.controller.item;
    opens com.unifisweproject.hotelsupplymanagement.controller.item to javafx.fxml;
    exports com.unifisweproject.hotelsupplymanagement.controller.supplier;
    opens com.unifisweproject.hotelsupplymanagement.controller.supplier to javafx.fxml;
    exports com.unifisweproject.hotelsupplymanagement.controller.order;
    opens com.unifisweproject.hotelsupplymanagement.controller.order to javafx.fxml;
    exports com.unifisweproject.hotelsupplymanagement.controller.supply;
    opens com.unifisweproject.hotelsupplymanagement.controller.supply to javafx.fxml;
}